### ISSUE TITLE
problem installing grayflow: cannot find -lX11

### ISSUE THREAD

**Issue by yasharne** [rubund/graywolf#10]
Hi
I'm trying to compile grayflow from source on centos4
after entering `make` command I get the following error:
`Linking C shared library libycadgraywolf.so
/usr/bin/ld: cannot find -lX11
collect2: ld returned 1 exit status
make[2]: *** [src/Ylib/libycadgraywolf.so.1.0.0] Error 1
make[1]: *** [src/Ylib/CMakeFiles/ycadgraywolf.dir/all] Error 2
make: *** [all] Error 2
`
How can I fix it?

**Comment by cirosantilli** [comment]
Maybe install https://rpmfind.net/linux/rpm2html/search.php?query=libX11-devel
