### ISSUE TITLE
libycadgraywolf.so: undefined reference to `cfree'

### ISSUE THREAD

**Issue by cirosantilli** [rubund/graywolf#16]
Ubuntu 17.10, `cmake .`, `make`, then:

```
[ 52%] Building C object src/twmc/CMakeFiles/TimberWolfMC.dir/__/date/date.c.o
[ 53%] Linking C executable TimberWolfMC
/home/ciro/git/graywolf/src/Ylib/libycadgraywolf.so: undefined reference to `cfree'
collect2: error: ld returned 1 exit status
src/twmc/CMakeFiles/TimberWolfMC.dir/build.make:1785: recipe for target 'src/twmc/TimberWolfMC' failed
```

**Comment by rubund** [comment]
Please check if the problems you are having have been fixed in this branch https://github.com/leviathanch/graywolf/

**Comment by cirosantilli** [comment]
This problem is solved by: https://github.com/rubund/graywolf/pull/15 I had made a patch but then noticed that one.

I noticed that repo has several commits on top, what is that repo? Is development moving there or is a merge expected at some time?
