### ISSUE TITLE
Compilation fails with make -j

### ISSUE THREAD

**Issue by cirosantilli** [rubund/graywolf#18]
If I try to use multiple cores with `make -j $(nproc)`, the compilation fails, I get an error at some point, and the exit status of `make` is not 0.

e1bf3196b985b9579051878ca951f1eca24d8a87 Ubuntu 17.10.

**Comment by rubund** [comment]
fixed on "master" and "dev". Thanks @StefanBruens  Sorry for taking forever to look at it.

**Comment by cirosantilli** [comment]
Great!
