### ISSUE TITLE
Bug in twsc/netgraph.c

### ISSUE THREAD

**Issue by RTimothyEdwards** [rubund/graywolf#20]
An efabless user was testing the synthesis flow with a tiny two-gate design, and graywolf appears to have issues with either the low gate count or more likely the low pin count, causing a segfault.  Debugging with valgrind, it appears that variable z_S is not allocating enough memory for the array.

Line 949 in twsc/netgraph.c:
   z_S[i] = (PINBOXPTR *)Ysafe_malloc( maxpin_numberS * sizeof(PINBOXPTR) ) ;

should be:
   z_S[i] = (PINBOXPTR *)Ysafe_malloc( ( maxpin_numberS + 1 ) * sizeof(PINBOXPTR) ) ;

The same change needs to be made to line 183.

---Tim

**Comment by rubund** [comment]
Thank you Tim: https://github.com/rubund/graywolf/commit/d42f1c46f45bf6e72c7d4b2fd65c2f0691561bd7
