### ISSUE TITLE
Master Branch Doesn't compile.

### ISSUE THREAD

**Issue by wbmaguire** [rubund/graywolf#7]
Hi There,

I cloned the repo and checked out the master branch.  It does not compile.

line 230 in buster.c in /src/lib fails to compile due to no INT return type.

Ybuster_addpt( INT xpos, INT ypos )
 INT xpos, ypos;
{
    if( xpos == ptS[cornerCountS].x && ypos == ptS[cornerCountS].y ){
	/* avoid redundant points */
	return;
    }
    /* increase the space if necessary */
    if( ++cornerCountS >= ptAllocS ){
	ptAllocS += EXPECTEDPTS ;
	ptS = YREALLOC( ptS,  ptAllocS, YBUSTBOX ) ;
    }
    ptS[cornerCountS].x = xpos ;
    ptS[cornerCountS].y = ypos ;
} /* end add_arb_pt */

There are more compile issues when this is fixed which I think are for very similar reasons.  Ie for draw.c 

/home/developer/qflow/graywolf/src/Ylib/draw.c:344:2: error: non-void function 'TWsetMode' should return a value [-Wreturn-type]
        return ;

Regards

Walter

**Comment by rubund** [comment]
Hi,

Thanks for telling. Which compiler do you use? It does compile at least
with GCC 5 on Linux in my environment. There are many ancient C constructs
in the code which cause warnings and maybe some of them have been escalated
to errors in your environment. So there's definitely things to do.

Cheers, Ruben
26. mai 2016 06:42 skrev "wbmaguire" <notifications@github.com>:

**Comment by wbmaguire** [comment]
Hi Ruben,

To the best of my knowledge, clang-3.5 on Ubuntu LTS14.04

I will try it with g++ 

Regards

Walter

**Comment by wbmaguire** [comment]
Hi Rubin,

G++ is more forgiving.  I was able to make it with this compiler.  

Thanks

Walter
